// <auto-generated />
using System;
using Commerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Commerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240325091443_updateforproductsandseedforcandy")]
    partial class updateforproductsandseedforcandy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Commerce.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsForLegalAge")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductFacts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96ed318a-2b63-4d5a-8d28-4338b7d542b2"),
                            Brand = "Marlboro",
                            Description = "Marlboro Gold är en mild tobaksblandning med en ren och balanserad smak. Perfekt för dem som föredrar en mildare rökupplevelse.",
                            Image = "marlboro-gold.jpg",
                            IsForLegalAge = true,
                            Name = "Marlboro Gold",
                            Price = 75.00m,
                            ProductCategoryId = new Guid("1faa3b8a-6f3d-4ad3-b21a-6e43887e4a57"),
                            ProductFacts = "Produktfakta: Förvaras vid högst 22.00°C för att bibehålla kvaliteten.",
                            ShortDescription = "Mild tobaksblandning med en ren och balanserad smak.",
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("5bc1db67-1f76-44c3-a6ef-8d9aa9627414"),
                            Brand = "Camel",
                            Description = "Camel Blue erbjuder en balanserad smak med en lätt och behaglig rökning. Perfekt för dem som söker en mildare och smidigare cigarettrökning.",
                            Image = "camel-blue.jpg",
                            IsForLegalAge = true,
                            Name = "Camel Blue",
                            Price = 70.00m,
                            ProductCategoryId = new Guid("1faa3b8a-6f3d-4ad3-b21a-6e43887e4a57"),
                            ProductFacts = "Produktfakta: Förvaras vid högst 22.00°C för att bibehålla kvaliteten.",
                            ShortDescription = "Balanserad smak med en lätt och behaglig rökning.",
                            Stock = 120
                        },
                        new
                        {
                            Id = new Guid("bc5107fc-e2f0-4c14-a2a2-6cf69dc52c39"),
                            Brand = "Winston",
                            Description = "Winston Red är en klassisk och robust cigarett med en djup och kraftfull smak. Perfekt för dem som föredrar en starkare rökupplevelse.",
                            Image = "winston-red.jpg",
                            IsForLegalAge = true,
                            Name = "Winston Red",
                            Price = 65.00m,
                            ProductCategoryId = new Guid("1faa3b8a-6f3d-4ad3-b21a-6e43887e4a57"),
                            ProductFacts = "Produktfakta: Förvaras vid högst 22.00°C för att bibehålla kvaliteten.",
                            ShortDescription = "Klassisk och robust cigarett med en djup och kraftfull smak.",
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("5dc3e742-d887-47c3-84f6-01973a01700b"),
                            Brand = "Lucky Strike",
                            Description = "Lucky Strike Original är en ikonisk cigarett med en distinkt och robust smakprofil. Perfekt för dem som letar efter en autentisk och tillfredsställande rökning.",
                            Image = "luckystrike-original.jpg",
                            IsForLegalAge = true,
                            Name = "Lucky Strike Original",
                            Price = 68.00m,
                            ProductCategoryId = new Guid("1faa3b8a-6f3d-4ad3-b21a-6e43887e4a57"),
                            ProductFacts = "Produktfakta: Förvaras vid högst 22.00°C för att bibehålla kvaliteten.",
                            ShortDescription = "Ikonisk cigarett med distinkt och robust smakprofil.",
                            Stock = 90
                        },
                        new
                        {
                            Id = new Guid("62ed95db-0f1e-4850-a889-16c66f3a0c0b"),
                            Brand = "Pall Mall",
                            Description = "Pall Mall Red är känd för sin robusta och intensiva smakprofil med en tydlig tobakston. Perfekt för dem som föredrar en kraftfull och fyllig rökning.",
                            Image = "pallmall-red.jpg",
                            IsForLegalAge = true,
                            Name = "Pall Mall Red",
                            Price = 62.00m,
                            ProductCategoryId = new Guid("1faa3b8a-6f3d-4ad3-b21a-6e43887e4a57"),
                            ProductFacts = "Produktfakta: Förvaras vid högst 22.00°C för att bibehålla kvaliteten.",
                            ShortDescription = "Robust och intensiv smakprofil med tydlig tobakston.",
                            Stock = 110
                        },
                        new
                        {
                            Id = new Guid("e877f4e0-e1d7-491f-9fa4-d7b74a1345c2"),
                            Brand = "Rothmans",
                            Description = "Rothmans Blue erbjuder en balanserad och len rökning med en distinkt tobakssmak. Perfekt för dem som söker en mild och behaglig rökupplevelse.",
                            Image = "rothmans-blue.jpg",
                            IsForLegalAge = true,
                            Name = "Rothmans Blue",
                            Price = 67.00m,
                            ProductCategoryId = new Guid("1faa3b8a-6f3d-4ad3-b21a-6e43887e4a57"),
                            ProductFacts = "Produktfakta: Förvaras vid högst 22.00°C för att bibehålla kvaliteten.",
                            ShortDescription = "Balanserad och len rökning med distinkt tobakssmak.",
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("26fe2d4e-95d3-46ad-9c19-12a0d4525453"),
                            Brand = "Davidoff",
                            Description = "Davidoff Gold är en premiumcigarett med en elegant och subtil smakprofil. Perfekt för dem som söker en sofistikerad och förstklassig rökupplevelse.",
                            Image = "davidoff-gold.jpg",
                            IsForLegalAge = true,
                            Name = "Davidoff Gold",
                            Price = 80.00m,
                            ProductCategoryId = new Guid("1faa3b8a-6f3d-4ad3-b21a-6e43887e4a57"),
                            ProductFacts = "Produktfakta: Förvaras vid högst 22.00°C för att bibehålla kvaliteten.",
                            ShortDescription = "Premiumcigarett med elegant och subtil smakprofil.",
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("769ff894-42fc-4d84-9dc8-87dcde6e28a2"),
                            Brand = "Benson & Hedges",
                            Description = "Benson & Hedges Gold erbjuder en rik och balanserad smak med en distinkt tobakskaraktär. Perfekt för dem som uppskattar en premium cigarettupplevelse.",
                            Image = "benson-hedges-gold.jpg",
                            IsForLegalAge = true,
                            Name = "Benson & Hedges Gold",
                            Price = 78.00m,
                            ProductCategoryId = new Guid("1faa3b8a-6f3d-4ad3-b21a-6e43887e4a57"),
                            ProductFacts = "Produktfakta: Förvaras vid högst 22.00°C för att bibehålla kvaliteten.",
                            ShortDescription = "Rik och balanserad smak med distinkt tobakskaraktär.",
                            Stock = 75
                        },
                        new
                        {
                            Id = new Guid("20175a2b-cb60-4a53-a134-69fbbd367af9"),
                            Brand = "Kent",
                            Description = "Kent Blue erbjuder en jämn och balanserad rökning med en distinkt tobakssmak. Perfekt för dem som söker en klassisk och tillfredsställande cigarettupplevelse.",
                            Image = "kent-blue.jpg",
                            IsForLegalAge = true,
                            Name = "Kent Blue",
                            Price = 73.00m,
                            ProductCategoryId = new Guid("1faa3b8a-6f3d-4ad3-b21a-6e43887e4a57"),
                            ProductFacts = "Produktfakta: Förvaras vid högst 22.00°C för att bibehålla kvaliteten.",
                            ShortDescription = "Jämn och balanserad rökning med distinkt tobakssmak.",
                            Stock = 85
                        },
                        new
                        {
                            Id = new Guid("69f5cc21-8280-4c49-8928-3e1d1523f8dc"),
                            Brand = "Prince",
                            Description = "Prince Rich Taste är en kraftfull och fyllig cigarett med en rik och intensiv smakprofil. Perfekt för dem som söker en djup och tillfredsställande rökning.",
                            Image = "prince-rich-taste.jpg",
                            IsForLegalAge = true,
                            Name = "Prince Rich Taste",
                            Price = 69.00m,
                            ProductCategoryId = new Guid("1faa3b8a-6f3d-4ad3-b21a-6e43887e4a57"),
                            ProductFacts = "Produktfakta: Förvaras vid högst 22.00°C för att bibehålla kvaliteten.",
                            ShortDescription = "Kraftfull och fyllig cigarett med en rik och intensiv smakprofil.",
                            Stock = 70
                        },
                        new
                        {
                            Id = new Guid("d43c78e4-eece-40f2-b7cc-4cd161727265"),
                            Brand = "PepsiCo",
                            Description = "Pepsi är en uppfriskande coladryck med en fräsch och djärv smak, perfekt för att stilla din törst på en varm sommardag eller som en uppiggande dryck under arbetet. Denna dryck är lämplig för personer i alla åldrar.",
                            Image = "pepsi.jpg",
                            IsForLegalAge = false,
                            Name = "Pepsi",
                            Price = 360m,
                            ProductCategoryId = new Guid("4c00f03e-e62f-430b-92c2-df95913a192b"),
                            ProductFacts = "Produktfakta: Förvaras svalt för bästa smakupplevelse.",
                            ShortDescription = "Frisk coladryck med en djärv smak.",
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("d1500077-4fe8-4c17-86a1-92c4a840f7f6"),
                            Brand = "The Coca-Cola Company",
                            Description = "Coca-Cola är en klassisk coladryck med en unik och förfriskande smak som har varit en favorit bland dryckesälskare över hela världen i generationer. Denna dryck är lämplig för personer i alla åldrar.",
                            Image = "cocacola.jpg",
                            IsForLegalAge = false,
                            Name = "Coca-Cola",
                            Price = 360m,
                            ProductCategoryId = new Guid("4c00f03e-e62f-430b-92c2-df95913a192b"),
                            ProductFacts = "Produktfakta: Bäst serverad kyld.",
                            ShortDescription = "Klassisk coladryck med unik smak.",
                            Stock = 120
                        },
                        new
                        {
                            Id = new Guid("e51998ad-3426-4ce7-bdfd-297ad6750c5e"),
                            Brand = "The Coca-Cola Company",
                            Description = "Fanta Orange är en tangy och söt apelsindryck som spricker av fruktig smak och är perfekt för att njuta av en het sommardag eller som en uppfriskande dryck under träning. Denna dryck är lämplig för personer i alla åldrar.",
                            Image = "fanta-orange.jpg",
                            IsForLegalAge = false,
                            Name = "Fanta Orange",
                            Price = 300m,
                            ProductCategoryId = new Guid("4c00f03e-e62f-430b-92c2-df95913a192b"),
                            ProductFacts = "Produktfakta: Skaka flaskan före öppning för bästa smak.",
                            ShortDescription = "Söt och fruktig apelsindryck.",
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("cbdcb109-4f18-4f86-81c2-50b820124c9b"),
                            Brand = "The Coca-Cola Company",
                            Description = "Sprite är en krispig och klar citron-lime soda med en uppfriskande smak som är idealisk för att stilla din törst och lämna dig känslan uppfriskad. Denna dryck är lämplig för personer i alla åldrar.",
                            Image = "sprite.jpg",
                            IsForLegalAge = false,
                            Name = "Sprite",
                            Price = 295m,
                            ProductCategoryId = new Guid("4c00f03e-e62f-430b-92c2-df95913a192b"),
                            ProductFacts = "Produktfakta: Bäst serverad väl kyld.",
                            ShortDescription = "Krispig citron-lime soda.",
                            Stock = 90
                        },
                        new
                        {
                            Id = new Guid("36989985-66a1-40da-90d9-ac24e0ab001f"),
                            Brand = "PepsiCo",
                            Description = "Mountain Dew är en djärv och citrusig soda med en kick av koffein för en energigivande boost som håller dig igång hela dagen. Denna dryck är lämplig för personer i alla åldrar.",
                            Image = "mountain-dew.jpg",
                            IsForLegalAge = false,
                            Name = "Mountain Dew",
                            Price = 425m,
                            ProductCategoryId = new Guid("4c00f03e-e62f-430b-92c2-df95913a192b"),
                            ProductFacts = "Produktfakta: Innehåller koffein.",
                            ShortDescription = "Citrusig soda med koffeinboost.",
                            Stock = 110
                        },
                        new
                        {
                            Id = new Guid("18dfc76e-6c67-4ec7-a6e9-8347f58577a3"),
                            Brand = "Keurig Dr Pepper",
                            Description = "Dr Pepper är en distinkt blandning av 23 smaker som skapar en unik och tillfredsställande smakupplevelse som har gjort den till en favorit bland dryckesälskare. Denna dryck är lämplig för personer i alla åldrar.",
                            Image = "drpepper.jpg",
                            IsForLegalAge = false,
                            Name = "Dr Pepper",
                            Price = 320m,
                            ProductCategoryId = new Guid("4c00f03e-e62f-430b-92c2-df95913a192b"),
                            ProductFacts = "Produktfakta: Innehåller koffein.",
                            ShortDescription = "Unik blandning av 23 smaker.",
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("54494de8-c138-4c62-b87b-cf622fc02ebc"),
                            Brand = "Schweppes",
                            Description = "Schweppes Tonic Water är ett krispigt och bubblande tonicvatten perfekt för att mixa med gin eller vodka och skapa en uppfriskande och läskande drink. Denna dryck är lämplig för personer i alla åldrar.",
                            Image = "schweppes-tonic.jpg",
                            IsForLegalAge = false,
                            Name = "Schweppes Tonic Water",
                            Price = 460m,
                            ProductCategoryId = new Guid("4c00f03e-e62f-430b-92c2-df95913a192b"),
                            ProductFacts = "Produktfakta: Bäst serverad med is.",
                            ShortDescription = "Bubblande tonicvatten.",
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("e0c299a9-8026-4c9b-a3c5-ba77d0397ece"),
                            Brand = "Nestlé",
                            Description = "Nestea Peach är en lätt och fruktig persikais med en uppfriskande smak och en mild sötma som gör den till det perfekta valet för att stilla din törst på en solig dag. Denna dryck är lämplig för personer i alla åldrar.",
                            Image = "nestea-peach.jpg",
                            IsForLegalAge = false,
                            Name = "Nestea Peach",
                            Price = 270m,
                            ProductCategoryId = new Guid("4c00f03e-e62f-430b-92c2-df95913a192b"),
                            ProductFacts = "Produktfakta: Innehåller naturliga smakämnen.",
                            ShortDescription = "Fruktig persikais.",
                            Stock = 90
                        },
                        new
                        {
                            Id = new Guid("c02a7a39-85e5-4d3d-9e11-d66294fc8e5a"),
                            Brand = "Unilever",
                            Description = "Lipton Iced Tea är en förfriskande iste med en balanserad och lätt söt smak som är perfekt för att njuta av på en varm sommardag eller som ett uppiggande alternativ till kaffe. Denna dryck är lämplig för personer i alla åldrar.",
                            Image = "lipton-iced-tea.jpg",
                            IsForLegalAge = false,
                            Name = "Lipton Iced Tea",
                            Price = 410m,
                            ProductCategoryId = new Guid("4c00f03e-e62f-430b-92c2-df95913a192b"),
                            ProductFacts = "Produktfakta: Innehåller naturliga smakämnen.",
                            ShortDescription = "Förfriskande iste.",
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("8eab0b08-1898-4b75-a046-a29a84659f10"),
                            Brand = "The Gatorade Company",
                            Description = "Gatorade Lemon-Lime är en elektrolytpackad dryck som hjälper till att återställa vätskebalansen och elektrolyterna efter träning. Denna dryck är lämplig för personer i alla åldrar.",
                            Image = "gatorade.jpg",
                            IsForLegalAge = false,
                            Name = "Gatorade Lemon-Lime",
                            Price = 220m,
                            ProductCategoryId = new Guid("4c00f03e-e62f-430b-92c2-df95913a192b"),
                            ProductFacts = "Produktfakta: Innehåller elektrolyter.",
                            ShortDescription = "Elektrolytpack.",
                            Stock = 70
                        },
                        new
                        {
                            Id = new Guid("b8e4cce7-f7bf-4acd-afde-4e9d2f5ac0a8"),
                            Brand = "Red Rain",
                            Description = "Intensiv energidryck med en kraftfull smak och en uppiggande effekt, perfekt för att hålla dig vaken och fokuserad under långa dagar. Denna produkt är avsedd för personer över laglig ålder.",
                            Image = "redrain.jpg",
                            IsForLegalAge = true,
                            Name = "Red Rain",
                            Price = 360.00m,
                            ProductCategoryId = new Guid("cc74f91b-91ac-4632-8636-15b7722fc3e7"),
                            ProductFacts = "Produktfakta:\n- Förvaras svalt och torrt\n- Innehåller koffein\n- Rekommenderas ej för barn, gravida eller ammande kvinnor",
                            ShortDescription = "Kraftfull energidryck.",
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("79586e5a-8d91-4b6d-8ff2-ae3940640d3b"),
                            Brand = "Monster Energy",
                            Description = "Kraftfull energidryck med en unik smakprofil som kombinerar söta och syrliga toner för en intensiv och uppfriskande smakupplevelse. Denna produkt är avsedd för personer över laglig ålder.",
                            Image = "monsterassault.jpg",
                            IsForLegalAge = true,
                            Name = "Monster Assault",
                            Price = 480.00m,
                            ProductCategoryId = new Guid("cc74f91b-91ac-4632-8636-15b7722fc3e7"),
                            ProductFacts = "Produktfakta:\n- Förvaras svalt och torrt\n- Innehåller koffein\n- Rekommenderas ej för barn, gravida eller ammande kvinnor",
                            ShortDescription = "Unik smakprofil.",
                            Stock = 70
                        },
                        new
                        {
                            Id = new Guid("c8966dd2-5bf5-4411-942f-f0a7e6f7f7a5"),
                            Brand = "Rockstar Energy",
                            Description = "Kraftfull energidryck med en fruktig smakexplosion av exotiska frukter och en extra boost av koffein för att hålla dig alert och redo för dagen. Denna produkt är avsedd för personer över laglig ålder.",
                            Image = "rockstarpunched.jpg",
                            IsForLegalAge = true,
                            Name = "Rockstar Punched",
                            Price = 540.00m,
                            ProductCategoryId = new Guid("cc74f91b-91ac-4632-8636-15b7722fc3e7"),
                            ProductFacts = "Produktfakta:\n- Förvaras svalt och torrt\n- Innehåller koffein\n- Rekommenderas ej för barn, gravida eller ammande kvinnor",
                            ShortDescription = "Fruktig smakexplosion.",
                            Stock = 90
                        },
                        new
                        {
                            Id = new Guid("f8b08f26-d250-485d-9ebf-25aa4a8fcb49"),
                            Brand = "VPX Bang",
                            Description = "Explosiv energidryck med en skarp och intensiv smak som ger dig den extra kick du behöver för att övervinna utmaningarna i din dagliga rutin. Denna produkt är avsedd för personer över laglig ålder.",
                            Image = "bangenergy.jpg",
                            IsForLegalAge = true,
                            Name = "Bang Energy",
                            Price = 600.00m,
                            ProductCategoryId = new Guid("cc74f91b-91ac-4632-8636-15b7722fc3e7"),
                            ProductFacts = "Produktfakta:\n- Förvaras svalt och torrt\n- Innehåller koffein\n- Rekommenderas ej för barn, gravida eller ammande kvinnor",
                            ShortDescription = "Explosiv smak.",
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("6931503e-c3e0-443a-85e5-c2363b9d9c74"),
                            Brand = "Xyience",
                            Description = "Högeffektiv energidryck med en läcker smak av blandade bär och en uppiggande blandning av vitaminer och antioxidanter för ökad energi och fokus. Denna produkt är avsedd för personer över laglig ålder.",
                            Image = "xyiencexenergy.jpg",
                            IsForLegalAge = true,
                            Name = "Xyience Xenergy",
                            Price = 420.00m,
                            ProductCategoryId = new Guid("cc74f91b-91ac-4632-8636-15b7722fc3e7"),
                            ProductFacts = "Produktfakta:\n- Förvaras svalt och torrt\n- Innehåller koffein\n- Rekommenderas ej för barn, gravida eller ammande kvinnor",
                            ShortDescription = "Högeffektiv energidryck.",
                            Stock = 85
                        },
                        new
                        {
                            Id = new Guid("7ad812f0-5df5-4464-8e0f-cc9b14da1653"),
                            Brand = "Full Throttle",
                            Description = "Kraftfull energidryck med en robust och kryddig smakprofil och en extra kick av koffein för att hjälpa dig att hålla dig vaken och alert. Denna produkt är avsedd för personer över laglig ålder.",
                            Image = "fullthrottle.jpg",
                            IsForLegalAge = true,
                            Name = "Full Throttle",
                            Price = 480.00m,
                            ProductCategoryId = new Guid("cc74f91b-91ac-4632-8636-15b7722fc3e7"),
                            ProductFacts = "Produktfakta:\n- Förvaras svalt och torrt\n- Innehåller koffein\n- Rekommenderas ej för barn, gravida eller ammande kvinnor",
                            ShortDescription = "Robust och kryddig smak.",
                            Stock = 75
                        },
                        new
                        {
                            Id = new Guid("b6b445d0-c4e3-4d69-86e1-d5714d0eb8d7"),
                            Brand = "NOS",
                            Description = "Högeffektiv energidryck med en frisk och fruktig smak av apelsin och en extra boost av taurin och koffein för att öka din prestanda och fokus. Denna produkt är avsedd för personer över laglig ålder.",
                            Image = "nosenergy.jpg",
                            IsForLegalAge = true,
                            Name = "NOS Energy Drink",
                            Price = 540.00m,
                            ProductCategoryId = new Guid("cc74f91b-91ac-4632-8636-15b7722fc3e7"),
                            ProductFacts = "Produktfakta:\n- Förvaras svalt och torrt\n- Innehåller koffein\n- Rekommenderas ej för barn, gravida eller ammande kvinnor",
                            ShortDescription = "Fruktig smak med taurinboost.",
                            Stock = 70
                        },
                        new
                        {
                            Id = new Guid("6d663a46-56f2-4c3b-8d2c-8017418ed100"),
                            Brand = "AMP Energy",
                            Description = "Kraftfull energidryck med en balanserad och uppfriskande smak samt en extra boost av koffein för att hjälpa dig att hålla dig vaken och alert under dagen. Denna produkt är avsedd för personer över laglig ålder.",
                            Image = "ampenergy.jpg",
                            IsForLegalAge = true,
                            Name = "AMP Energy",
                            Price = 420.00m,
                            ProductCategoryId = new Guid("cc74f91b-91ac-4632-8636-15b7722fc3e7"),
                            ProductFacts = "Produktfakta:\n- Förvaras svalt och torrt\n- Innehåller koffein\n- Rekommenderas ej för barn, gravida eller ammande kvinnor",
                            ShortDescription = "Balanserad och uppfriskande smak.",
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("f7b1049f-463c-41da-a5ff-69f17bbf55cb"),
                            Brand = "Godis AB",
                            Description = "Saftiga och mjuka geléhallon i olika färger och smaker som garanterat kommer att tillfredsställa ditt sötsug.",
                            Image = "geléhallon.jpg",
                            IsForLegalAge = false,
                            Name = "Geléhallon",
                            Price = 8.00m,
                            ProductCategoryId = new Guid("d58f87f4-7378-447a-93d4-b888fbecfb6e"),
                            ProductFacts = "Produktfakta:\n- Fri från gelatin\n- Kan innehålla spår av gluten\n- Ej lämplig för personer med gelatinallergi",
                            ShortDescription = "Saftiga geléhallon.",
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("ddf823e5-e368-40f4-a747-74592340e6fe"),
                            Brand = "Godis AB",
                            Description = "Klassiska lakritssnören med en intensiv och fyllig smak av lakrits som kommer att tillfredsställa dina smaklökar.",
                            Image = "lakritssnören.jpg",
                            IsForLegalAge = false,
                            Name = "Lakritssnören",
                            Price = 10.00m,
                            ProductCategoryId = new Guid("d58f87f4-7378-447a-93d4-b888fbecfb6e"),
                            ProductFacts = "Produktfakta:\n- Innehåller gluten\n- Ej lämplig för personer med glutenintolerans\n- Kan innehålla spår av gelatin",
                            ShortDescription = "Klassiska lakritssnören.",
                            Stock = 120
                        },
                        new
                        {
                            Id = new Guid("fd0c9885-7f4c-4011-a6e1-4c4c838bda45"),
                            Brand = "Chokladfabriken AB",
                            Description = "Lyxiga chokladpraliner i olika former och fyllningar som smälter i munnen och ger en ljuvlig smakupplevelse.",
                            Image = "chokladpraliner.jpg",
                            IsForLegalAge = false,
                            Name = "Chokladpraliner",
                            Price = 12.00m,
                            ProductCategoryId = new Guid("d58f87f4-7378-447a-93d4-b888fbecfb6e"),
                            ProductFacts = "Produktfakta:\n- Innehåller mjölk och nötter\n- Kan innehålla spår av gluten och soja\n- Ej lämplig för personer med allergier mot mjölk eller nötter",
                            ShortDescription = "Lyxiga chokladpraliner.",
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("ee155a6e-bf18-41f0-8ef5-b17719d005af"),
                            Brand = "Godis AB",
                            Description = "Syrliga och saftiga surkolor som ger en smakexplosion i munnen och är perfekta för dig som älskar det sura godiset.",
                            Image = "surkola.jpg",
                            IsForLegalAge = false,
                            Name = "Surkola",
                            Price = 6.00m,
                            ProductCategoryId = new Guid("d58f87f4-7378-447a-93d4-b888fbecfb6e"),
                            ProductFacts = "Produktfakta:\n- Kan innehålla spår av gelatin\n- Ej lämplig för personer med känslig magslemhinna\n- Överdriven konsumtion kan vara skadlig för tänderna",
                            ShortDescription = "Syrliga surkolor.",
                            Stock = 90
                        },
                        new
                        {
                            Id = new Guid("ad2376e2-cdf2-4bc9-ba35-86e40cd8b97d"),
                            Brand = "Godis AB",
                            Description = "Söta och saftiga jordgubbsremmar som är perfekta att tugga på och njuta av en underbar smak av solmogna jordgubbar.",
                            Image = "jordgubbsremmar.jpg",
                            IsForLegalAge = false,
                            Name = "Jordgubbsremmar",
                            Price = 8.00m,
                            ProductCategoryId = new Guid("d58f87f4-7378-447a-93d4-b888fbecfb6e"),
                            ProductFacts = "Produktfakta:\n- Fri från gelatin\n- Kan innehålla spår av mjölk och soja\n- Ej lämplig för personer med allergier mot jordgubbar",
                            ShortDescription = "Söta jordgubbsremmar.",
                            Stock = 110
                        },
                        new
                        {
                            Id = new Guid("fe27c2fa-7285-4fb3-9204-0b5b7c87f379"),
                            Brand = "Godis AB",
                            Description = "Mjuka och sega karamellkolor i olika färger och smaker som kommer att föra dig tillbaka till barndomens godisminnen.",
                            Image = "karamellkolor.jpg",
                            IsForLegalAge = false,
                            Name = "Karamellkolor",
                            Price = 7.00m,
                            ProductCategoryId = new Guid("d58f87f4-7378-447a-93d4-b888fbecfb6e"),
                            ProductFacts = "Produktfakta:\n- Fri från gelatin\n- Kan innehålla spår av mjölk och nötter\n- Ej lämplig för personer med allergier mot mjölk eller nötter",
                            ShortDescription = "Mjuka karamellkolor.",
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("93ffddc9-900c-4736-a9c9-6be1a85989c9"),
                            Brand = "Godis AB",
                            Description = "Surisar är små, syrliga godisbitar som är en perfekt kombination av sötma och surhet och ger dig en smakfull upplevelse.",
                            Image = "surisar.jpg",
                            IsForLegalAge = false,
                            Name = "Surisar",
                            Price = 9.00m,
                            ProductCategoryId = new Guid("d58f87f4-7378-447a-93d4-b888fbecfb6e"),
                            ProductFacts = "Produktfakta:\n- Kan innehålla spår av gelatin\n- Ej lämplig för personer med känslig magslemhinna\n- Överdriven konsumtion kan vara skadlig för tänderna",
                            ShortDescription = "Små syrliga surisar.",
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("f8e56652-bcc1-40ec-b6cc-b5a2c882e76c"),
                            Brand = "Godis AB",
                            Description = "Krispiga och luftiga maränger täckta med choklad och strössel som smälter i munnen och ger en himmelsk smakupplevelse.",
                            Image = "marängsviss.jpg",
                            IsForLegalAge = false,
                            Name = "Marängsviss",
                            Price = 11.00m,
                            ProductCategoryId = new Guid("d58f87f4-7378-447a-93d4-b888fbecfb6e"),
                            ProductFacts = "Produktfakta:\n- Kan innehålla spår av ägg och mjölk\n- Ej lämplig för personer med ägg- eller mjölkallergi\n- Överdriven konsumtion kan vara skadlig för tänderna",
                            ShortDescription = "Krispiga marängsviss.",
                            Stock = 90
                        },
                        new
                        {
                            Id = new Guid("1ea26f7c-bd3c-40a2-a286-9f7b2a570bed"),
                            Brand = "Godis AB",
                            Description = "Mjukt och luftigt skumgodis i olika färger och former som smälter i munnen och ger en söt och behaglig smakupplevelse.",
                            Image = "skumgodis.jpg",
                            IsForLegalAge = false,
                            Name = "Skumgodis",
                            Price = 9.00m,
                            ProductCategoryId = new Guid("d58f87f4-7378-447a-93d4-b888fbecfb6e"),
                            ProductFacts = "Produktfakta:\n- Fri från gelatin\n- Kan innehålla spår av mjölk och soja\n- Ej lämplig för personer med allergier mot mjölk eller soja",
                            ShortDescription = "Mjukt skumgodis.",
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("1abf4be2-bac4-4f3f-84d9-f485962a403d"),
                            Brand = "Godis AB",
                            Description = "Salta fiskar är små godisbitar som kombinerar den salta smaken av lakrits med en söt och seg konsistens för en spännande smakupplevelse.",
                            Image = "salta-fiskar.jpg",
                            IsForLegalAge = false,
                            Name = "Salta Fiskar",
                            Price = 8.00m,
                            ProductCategoryId = new Guid("d58f87f4-7378-447a-93d4-b888fbecfb6e"),
                            ProductFacts = "Produktfakta:\n- Innehåller gluten\n- Ej lämplig för personer med glutenintolerans\n- Kan innehålla spår av gelatin",
                            ShortDescription = "Salta lakritsfiskar.",
                            Stock = 70
                        },
                        new
                        {
                            Id = new Guid("a3e389d1-5891-4037-8f6b-4922d5a35a60"),
                            Brand = "Hershey's",
                            Description = "Creamy and delicious milk chocolate bar that melts in your mouth, perfect for satisfying your sweet cravings.",
                            Image = "milk-chocolate-bar.jpg",
                            IsForLegalAge = false,
                            Name = "Milk Chocolate Bar",
                            Price = 15.50m,
                            ProductCategoryId = new Guid("87242b00-6f72-4caa-b687-b105001e1ad3"),
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("88b2e422-37a9-4d56-8469-d53f780c439b"),
                            Brand = "Haribo",
                            Description = "Chewy and fruity gummy bears in a variety of colors and flavors, perfect for kids and adults alike.",
                            Image = "gummy-bears.jpg",
                            IsForLegalAge = false,
                            Name = "Gummy Bears",
                            Price = 12.75m,
                            ProductCategoryId = new Guid("87242b00-6f72-4caa-b687-b105001e1ad3"),
                            Stock = 120
                        },
                        new
                        {
                            Id = new Guid("25e4dc55-6f57-4a6f-bd22-3b4d0cf8ed2f"),
                            Brand = "Trolli",
                            Description = "Tangy and chewy sour worms with a zesty coating that adds a burst of flavor with every bite, sure to tantalize your taste buds.",
                            Image = "sour-worms.jpg",
                            IsForLegalAge = false,
                            Name = "Sour Worms",
                            Price = 11.25m,
                            ProductCategoryId = new Guid("87242b00-6f72-4caa-b687-b105001e1ad3"),
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("6d437f17-22b3-4f1d-b6b1-8a29cb2b9c6f"),
                            Brand = "Jelly Belly",
                            Description = "Assorted jelly beans with a mix of fruity flavors and vibrant colors, perfect for snacking or as a sweet treat for special occasions.",
                            Image = "jelly-beans.jpg",
                            IsForLegalAge = false,
                            Name = "Jelly Beans",
                            Price = 10.75m,
                            ProductCategoryId = new Guid("87242b00-6f72-4caa-b687-b105001e1ad3"),
                            Stock = 90
                        },
                        new
                        {
                            Id = new Guid("6e860a28-5102-499d-ae76-6d857f77e390"),
                            Brand = "Reese's",
                            Description = "Creamy peanut butter encased in smooth milk chocolate cups, a classic combination that's loved by chocolate and peanut butter enthusiasts.",
                            Image = "peanut-butter-cups.jpg",
                            IsForLegalAge = false,
                            Name = "Peanut Butter Cups",
                            Price = 18.50m,
                            ProductCategoryId = new Guid("87242b00-6f72-4caa-b687-b105001e1ad3"),
                            Stock = 110
                        },
                        new
                        {
                            Id = new Guid("c6141e15-dff1-46a1-a8ec-7a2791212a7b"),
                            Brand = "Red Vines",
                            Description = "Chewy and flavorful licorice twists with a hint of sweetness, perfect for satisfying your candy cravings anytime.",
                            Image = "licorice-twists.jpg",
                            IsForLegalAge = false,
                            Name = "Licorice Twists",
                            Price = 14.75m,
                            ProductCategoryId = new Guid("87242b00-6f72-4caa-b687-b105001e1ad3"),
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("4d1c66d4-9e5d-4cb4-bc87-8c47a4c7a1e0"),
                            Brand = "Mars",
                            Description = "Colorful and crunchy candy-coated chocolates that are fun to eat and perfect for sharing with friends and family.",
                            Image = "mms.jpg",
                            IsForLegalAge = false,
                            Name = "M&M's",
                            Price = 13.25m,
                            ProductCategoryId = new Guid("87242b00-6f72-4caa-b687-b105001e1ad3"),
                            Stock = 90
                        },
                        new
                        {
                            Id = new Guid("2c0e93d1-739a-4229-b4e1-e7cb2e7b69ac"),
                            Brand = "Mars",
                            Description = "Indulgent candy bar with layers of nougat, caramel, and peanuts covered in milk chocolate, providing a satisfying blend of flavors and textures.",
                            Image = "snickers.jpg",
                            IsForLegalAge = false,
                            Name = "Snickers",
                            Price = 16.00m,
                            ProductCategoryId = new Guid("87242b00-6f72-4caa-b687-b105001e1ad3"),
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("9e0a995a-12a1-448b-95c2-314e1884e57f"),
                            Brand = "Nestlé",
                            Description = "Classic wafer fingers covered in smooth milk chocolate, offering a crispy and creamy treat that's perfect for a quick snack or dessert.",
                            Image = "kitkat.jpg",
                            IsForLegalAge = false,
                            Name = "Kit Kat",
                            Price = 17.50m,
                            ProductCategoryId = new Guid("87242b00-6f72-4caa-b687-b105001e1ad3"),
                            Stock = 85
                        },
                        new
                        {
                            Id = new Guid("b7b8c7b8-7896-4ad1-8493-fdbb497b3a4e"),
                            Brand = "Mars",
                            Description = "Crunchy biscuit sticks topped with caramel and coated in milk chocolate, providing a deliciously satisfying combination of textures and flavors.",
                            Image = "twix.jpg",
                            IsForLegalAge = false,
                            Name = "Twix",
                            Price = 15.75m,
                            ProductCategoryId = new Guid("87242b00-6f72-4caa-b687-b105001e1ad3"),
                            Stock = 70
                        },
                        new
                        {
                            Id = new Guid("00fa2179-1a79-437e-9514-9e48857f51f5"),
                            Brand = "Swedish Match",
                            Description = "General Classic Portion är en traditionell snus med en tydlig tobakssmak och en balanserad fuktighet. Perfekt för dem som uppskattar en klassisk och pålitlig snusupplevelse.",
                            Image = "general-classic.jpg",
                            IsForLegalAge = true,
                            Name = "General Classic Portion",
                            Price = 45.00m,
                            ProductCategoryId = new Guid("572d1a92-5e15-4602-b150-01a2923224c6"),
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("09c13be3-5ed9-4c53-9a51-8cc09e00c08c"),
                            Brand = "Swedish Match",
                            Description = "Ettan Original Portion är en klassisk snus med en rund och rik smakprofil. Perfekt för dem som söker en välbalanserad och traditionell snusupplevelse.",
                            Image = "ettan-original.jpg",
                            IsForLegalAge = true,
                            Name = "Ettan Original Portion",
                            Price = 50.00m,
                            ProductCategoryId = new Guid("572d1a92-5e15-4602-b150-01a2923224c6"),
                            Stock = 120
                        },
                        new
                        {
                            Id = new Guid("130b0491-3cf6-4d52-9d25-8e7c5a7bb31e"),
                            Brand = "Swedish Match",
                            Description = "Göteborgs Rapé White Portion är en mild och frisk snus med en lätt tobakssmak och inslag av citrus och lavendel. Perfekt för dem som söker en uppfriskande och aromatisk snusupplevelse.",
                            Image = "goteborgs-rape-white.jpg",
                            IsForLegalAge = true,
                            Name = "Göteborgs Rapé White Portion",
                            Price = 48.00m,
                            ProductCategoryId = new Guid("572d1a92-5e15-4602-b150-01a2923224c6"),
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("16bca26d-4d89-468b-8f22-90cc5e9b26db"),
                            Brand = "Skruf",
                            Description = "Skruf Super White Slim Fresh är en vit och tobaksfri snus med en frisk och mintig smak. Perfekt för dem som vill njuta av en snusupplevelse utan tobak.",
                            Image = "skruf-super-white.jpg",
                            IsForLegalAge = true,
                            Name = "Skruf Super White Slim Fresh",
                            Price = 55.00m,
                            ProductCategoryId = new Guid("572d1a92-5e15-4602-b150-01a2923224c6"),
                            Stock = 90
                        },
                        new
                        {
                            Id = new Guid("2e0b90c4-8a10-47e2-9a2f-17432d0790ab"),
                            Brand = "Swedish Match",
                            Description = "Nick & Johnny Green Ice White är en kraftfull snus med en svalkande smak av mint och en frisk tobakston. Perfekt för dem som söker en intensiv och uppfriskande snusupplevelse.",
                            Image = "nick-johnny-green-ice.jpg",
                            IsForLegalAge = true,
                            Name = "Nick & Johnny Green Ice White",
                            Price = 52.00m,
                            ProductCategoryId = new Guid("572d1a92-5e15-4602-b150-01a2923224c6"),
                            Stock = 110
                        },
                        new
                        {
                            Id = new Guid("341c55fb-1874-4b97-b23a-d9069ed4dc4f"),
                            Brand = "Skruf",
                            Description = "Skruf Original Portion är en klassisk svensk snus med en balanserad och robust tobakssmak. Perfekt för dem som uppskattar en traditionell och pålitlig snusupplevelse.",
                            Image = "skruf-original.jpg",
                            IsForLegalAge = true,
                            Name = "Skruf Original Portion",
                            Price = 47.00m,
                            ProductCategoryId = new Guid("572d1a92-5e15-4602-b150-01a2923224c6"),
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("35e4481e-12ac-41ae-9dbb-d3b29ac7479b"),
                            Brand = "Kronan",
                            Description = "Kronan Original Portion är en klassisk och robust snus med en fyllig tobakssmak. Perfekt för dem som söker en kraftfull och traditionell snusupplevelse.",
                            Image = "kronan-original.jpg",
                            IsForLegalAge = true,
                            Name = "Kronan Original Portion",
                            Price = 46.00m,
                            ProductCategoryId = new Guid("572d1a92-5e15-4602-b150-01a2923224c6"),
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("3d85573a-5b41-4d3d-9f4f-3ee28dd01e54"),
                            Brand = "Fiedler & Lundgren",
                            Description = "Granit White Portion är en mild och rund snus med en ren tobakssmak. Perfekt för dem som söker en diskret och behaglig snusupplevelse.",
                            Image = "granit-white.jpg",
                            IsForLegalAge = true,
                            Name = "Granit White Portion",
                            Price = 49.00m,
                            ProductCategoryId = new Guid("572d1a92-5e15-4602-b150-01a2923224c6"),
                            Stock = 85
                        },
                        new
                        {
                            Id = new Guid("51669ac3-fffd-4663-9816-d46016a30a2c"),
                            Brand = "V2 Tobacco",
                            Description = "Thunder X Slim White Dry är en extra stark snus med en kraftig tobakssmak och en låg fuktighetsnivå. Perfekt för dem som söker en intensiv och långvarig snusupplevelse.",
                            Image = "thunder-x-slim.jpg",
                            IsForLegalAge = true,
                            Name = "Thunder X Slim White Dry",
                            Price = 54.00m,
                            ProductCategoryId = new Guid("572d1a92-5e15-4602-b150-01a2923224c6"),
                            Stock = 75
                        },
                        new
                        {
                            Id = new Guid("64b10bb4-6b11-4399-9480-e8c4af7f2064"),
                            Brand = "Gotlandssnus",
                            Description = "Jakobsson's Melon Mini Portion är en frisk och söt snus med en välbalanserad smak av saftig melon. Perfekt för dem som söker en mild och fruktig snusupplevelse.",
                            Image = "jakobssons-melon.jpg",
                            IsForLegalAge = true,
                            Name = "Jakobsson's Melon Mini Portion",
                            Price = 53.00m,
                            ProductCategoryId = new Guid("572d1a92-5e15-4602-b150-01a2923224c6"),
                            Stock = 70
                        },
                        new
                        {
                            Id = new Guid("f13e2e28-9361-4267-b06c-d03b89290561"),
                            Brand = "Grill Masters",
                            Description = "En klassisk blandning av kryddor och kryddor, inklusive paprika, vitlökspulver, brunt socker och cayennepeppar, perfekt för att lägga till smak och djup till grillat kött, fågel och grönsaker.",
                            Image = "classic-bbq-rub.jpg",
                            IsForLegalAge = false,
                            Name = "Klassisk BBQ Rub",
                            Price = 35.00m,
                            ProductCategoryId = new Guid("d72b840d-44ab-4205-b526-02111d87691b"),
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("b59e0917-c529-497d-a37d-26b97d8f451f"),
                            Brand = "Grill Masters",
                            Description = "En rökig och kryddig blandning av chipotlepeppar, rökt paprika, vitlök och lök, perfekt för att lägga till en djärv och smakrik kick till grillat kött, skaldjur och grönsaker.",
                            Image = "chipotle-seasoning.jpg",
                            IsForLegalAge = false,
                            Name = "Rökig Chipotle-krydda",
                            Price = 38.00m,
                            ProductCategoryId = new Guid("d72b840d-44ab-4205-b526-02111d87691b"),
                            Stock = 35
                        },
                        new
                        {
                            Id = new Guid("f567409b-f435-4b97-9ba7-51bcf92a4bbf"),
                            Brand = "Grill Masters",
                            Description = "En söt och kryddig glasyr gjord med honung, bourbonwhiskey, senap och kryddor, perfekt för att karamellisera grillat kött, kyckling och revben.",
                            Image = "honey-bourbon-glaze.jpg",
                            IsForLegalAge = false,
                            Name = "Honungsbourbon-glasyr",
                            Price = 40.00m,
                            ProductCategoryId = new Guid("d72b840d-44ab-4205-b526-02111d87691b"),
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("93b5a3de-2d08-45cd-b804-88d93117e2c7"),
                            Brand = "Grill Masters",
                            Description = "En eldig blandning av Cajun-kryddor, inklusive cayennepeppar, paprika, vitlök och lök, perfekt för att lägga till en djärv och zestig smak till grillad räkor, fisk och fågel.",
                            Image = "cajun-rub.jpg",
                            IsForLegalAge = false,
                            Name = "Kryddig Cajun Rub",
                            Price = 36.00m,
                            ProductCategoryId = new Guid("d72b840d-44ab-4205-b526-02111d87691b"),
                            Stock = 45
                        },
                        new
                        {
                            Id = new Guid("eabf62f8-cb30-45f5-aa14-b63b6c0631e4"),
                            Brand = "Grill Masters",
                            Description = "En rik och smakfull glasyr gjord med lönnsirap, bourbonwhiskey, brunt socker och kryddor, perfekt för att lägga till en söt och rökig finish till grillat fläskkött, nötkött och kyckling.",
                            Image = "maple-bourbon-glaze.jpg",
                            IsForLegalAge = false,
                            Name = "Lönnsirap Bourbon-glasyr",
                            Price = 42.00m,
                            ProductCategoryId = new Guid("d72b840d-44ab-4205-b526-02111d87691b"),
                            Stock = 38
                        },
                        new
                        {
                            Id = new Guid("c58f02db-fa44-47d1-97d5-4e1778a12e07"),
                            Brand = "Grill Masters",
                            Description = "En doftande och kryddig marinad gjord med vitlök, rosmarin, timjan och citron, perfekt för att infusera grillat kött, kyckling och grönsaker med läcker smak.",
                            Image = "garlic-herb-marinade.jpg",
                            IsForLegalAge = false,
                            Name = "Vitlök och örtmarinad",
                            Price = 37.00m,
                            ProductCategoryId = new Guid("d72b840d-44ab-4205-b526-02111d87691b"),
                            Stock = 42
                        },
                        new
                        {
                            Id = new Guid("16aee36f-d1cb-4979-88fc-b7fc540e8360"),
                            Brand = "Grill Masters",
                            Description = "En kryddig och rökig barbecue-sås med en hint av sötma, perfekt för att smeta över ribs, kycklingvingar och hamburgare för en autentisk smak av Kansas City.",
                            Image = "kansas-city-bbq-sauce.jpg",
                            IsForLegalAge = false,
                            Name = "Kansas City BBQ-sås",
                            Price = 39.00m,
                            ProductCategoryId = new Guid("d72b840d-44ab-4205-b526-02111d87691b"),
                            Stock = 37
                        },
                        new
                        {
                            Id = new Guid("aba0e880-9edb-44a2-96d8-a0cf508b5ef2"),
                            Brand = "Kryddmästarna",
                            Description = "En klassisk blandning av italienska örter, inklusive basilika, oregano, rosmarin och timjan, perfekt för att lägga till smak till pasta, pizza och sallader.",
                            Image = "italian-seasoning.jpg",
                            IsForLegalAge = false,
                            Name = "Italiensk Kryddblandning",
                            Price = 25.00m,
                            ProductCategoryId = new Guid("aba0e880-9edb-44a2-96d8-a0cf508b5ef2"),
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("6c0b83db-34aa-4de7-bf2f-3b2aa4c1a14a"),
                            Brand = "Kryddmästarna",
                            Description = "En kryddig blandning av mexikanska kryddor, inklusive chilipulver, spiskummin, paprika och vitlök, perfekt för att ge en extra kick till tacos, burritos och fajitas.",
                            Image = "mexican-spice-mix.jpg",
                            IsForLegalAge = false,
                            Name = "Mexikansk Kryddblandning",
                            Price = 30.00m,
                            ProductCategoryId = new Guid("aba0e880-9edb-44a2-96d8-a0cf508b5ef2"),
                            Stock = 35
                        },
                        new
                        {
                            Id = new Guid("3f8dc7e5-2c18-472a-a847-97912e2d0879"),
                            Brand = "Kryddmästarna",
                            Description = "En aromatisk blandning av asiatiska kryddor, inklusive ingefära, vitlök, sojasås och sesamfrön, perfekt för att krydda wokrätter, nudlar och risrätter.",
                            Image = "asian-stir-fry-seasoning.jpg",
                            IsForLegalAge = false,
                            Name = "Asiatisk Wokkrydda",
                            Price = 28.00m,
                            ProductCategoryId = new Guid("aba0e880-9edb-44a2-96d8-a0cf508b5ef2"),
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("91963e79-b529-40c0-94cf-4975e8464c5b"),
                            Brand = "Kryddmästarna",
                            Description = "En smakfull blandning av medelhavskryddor, inklusive persilja, timjan, basilika och oregano, perfekt för att krydda grillat kött, grönsaker och skaldjur.",
                            Image = "mediterranean-herb-mix.jpg",
                            IsForLegalAge = false,
                            Name = "Medelhavsörterblandning",
                            Price = 27.00m,
                            ProductCategoryId = new Guid("aba0e880-9edb-44a2-96d8-a0cf508b5ef2"),
                            Stock = 45
                        },
                        new
                        {
                            Id = new Guid("5bcf6b1c-bd7e-4e7d-8803-c62db9d5f777"),
                            Brand = "Kryddmästarna",
                            Description = "En doftande blandning av indiska kryddor, inklusive currypulver, gurkmeja, spiskummin och koriander, perfekt för att ge djup och smak till curryrätter, grytor och risrätter.",
                            Image = "indian-curry-spice.jpg",
                            IsForLegalAge = false,
                            Name = "Indisk Currykrydda",
                            Price = 32.00m,
                            ProductCategoryId = new Guid("aba0e880-9edb-44a2-96d8-a0cf508b5ef2"),
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("ca01c900-ff13-47e3-81a4-fdaddc905688"),
                            Brand = "Kryddmästarna",
                            Description = "En traditionell blandning av provencalska örter, inklusive lavendel, mejram, libbsticka och timjan, perfekt för att krydda rostat kött, grönsaker och soppor med en fransk touch.",
                            Image = "herbes-de-provence.jpg",
                            IsForLegalAge = false,
                            Name = "Herbes de Provence",
                            Price = 26.00m,
                            ProductCategoryId = new Guid("aba0e880-9edb-44a2-96d8-a0cf508b5ef2"),
                            Stock = 38
                        },
                        new
                        {
                            Id = new Guid("c7d45df1-fde9-4b7d-b3dc-186ea8b46f6a"),
                            Brand = "Kryddmästarna",
                            Description = "En doftande blandning av örter från Mellanöstern, inklusive timjan, sumak, sesamfrön och oregano, perfekt för att strö över flatbröd, sallader och dippsåser.",
                            Image = "zaatar.jpg",
                            IsForLegalAge = false,
                            Name = "Za'atar från Mellanöstern",
                            Price = 29.00m,
                            ProductCategoryId = new Guid("aba0e880-9edb-44a2-96d8-a0cf508b5ef2"),
                            Stock = 33
                        },
                        new
                        {
                            Id = new Guid("0f64b525-6c14-4815-8a7a-7e202c5352cf"),
                            Brand = "Kryddmästarna",
                            Description = "En kryddig och aromatisk blandning av karibiska kryddor, inklusive kryddpeppar, kanel, muskotnöt och habaneropeppar, perfekt för att ge värme och smak till grillat kött, skaldjur och grönsaker.",
                            Image = "caribbean-jerk-seasoning.jpg",
                            IsForLegalAge = false,
                            Name = "Karibisk Jerkkrydda",
                            Price = 31.00m,
                            ProductCategoryId = new Guid("aba0e880-9edb-44a2-96d8-a0cf508b5ef2"),
                            Stock = 27
                        },
                        new
                        {
                            Id = new Guid("08d3cc5b-9ac4-4d8b-b7de-d5c16f1c83b5"),
                            Brand = "Kryddmästarna",
                            Description = "En klassisk blandning av franska örter, inklusive rosmarin, timjan, mejram och dragon, perfekt för att krydda rostat kött, fågel och grönsaker.",
                            Image = "french-herbes-de-provence.jpg",
                            IsForLegalAge = false,
                            Name = "Franska Herbes de Provence",
                            Price = 26.50m,
                            ProductCategoryId = new Guid("aba0e880-9edb-44a2-96d8-a0cf508b5ef2"),
                            Stock = 36
                        },
                        new
                        {
                            Id = new Guid("ed700aa7-38d8-45b4-80f3-4954696fb999"),
                            Brand = "Kryddmästarna",
                            Description = "En doftande och smakrik blandning av asiatiska kryddor, inklusive gurkmeja, ingefära, spiskummin och koriander, perfekt för att ge en exotisk twist till curryrätter, soppor och wokrätter.",
                            Image = "asian-curry-powder.jpg",
                            IsForLegalAge = false,
                            Name = "Asiatisk Currykrydda",
                            Price = 30.50m,
                            ProductCategoryId = new Guid("aba0e880-9edb-44a2-96d8-a0cf508b5ef2"),
                            Stock = 29
                        },
                        new
                        {
                            Id = new Guid("b293d089-4d2b-4099-9a2c-28cb0a2ef365"),
                            Brand = "Kryddmästarna",
                            Description = "Färsk och aromatisk basilika perfekt för att använda i pesto, tomatsås, sallader och italienska rätter.",
                            Image = "basil.jpg",
                            IsForLegalAge = false,
                            Name = "Basilika",
                            Price = 15.00m,
                            ProductCategoryId = new Guid("dc3d8822-1dec-4569-a5c7-77faea561d56"),
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("9c95338e-9a30-4e3d-b80b-bae349a82d69"),
                            Brand = "Kryddmästarna",
                            Description = "Aromatisk och talliknande rosmarin som passar utmärkt till att krydda rostad potatis, grillat kött och grönsaksrätter.",
                            Image = "rosemary.jpg",
                            IsForLegalAge = false,
                            Name = "Rosmarin",
                            Price = 18.00m,
                            ProductCategoryId = new Guid("dc3d8822-1dec-4569-a5c7-77faea561d56"),
                            Stock = 45
                        },
                        new
                        {
                            Id = new Guid("07106d71-5e10-47f2-8b11-5da537d62134"),
                            Brand = "Kryddmästarna",
                            Description = "Aromatisk och jordig timjan som passar utmärkt till att krydda grytor, soppor, kyckling och fiskrätter.",
                            Image = "thyme.jpg",
                            IsForLegalAge = false,
                            Name = "Timjan",
                            Price = 16.00m,
                            ProductCategoryId = new Guid("dc3d8822-1dec-4569-a5c7-77faea561d56"),
                            Stock = 55
                        },
                        new
                        {
                            Id = new Guid("e07803fb-760a-42a0-8c72-c7cf236c66a0"),
                            Brand = "Kryddmästarna",
                            Description = "Aromatisk och robust oregano som passar utmärkt till att krydda pizza, pasta, sallader och grekiska rätter.",
                            Image = "oregano.jpg",
                            IsForLegalAge = false,
                            Name = "Oregano",
                            Price = 14.00m,
                            ProductCategoryId = new Guid("dc3d8822-1dec-4569-a5c7-77faea561d56"),
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("19cd6f32-1a29-4797-a3f6-86b1a1b2aeb1"),
                            Brand = "Kryddmästarna",
                            Description = "Färsk och krispig dill som passar utmärkt till att krydda fiskrätter, såser, sallader och potatis.",
                            Image = "dill.jpg",
                            IsForLegalAge = false,
                            Name = "Dill",
                            Price = 17.00m,
                            ProductCategoryId = new Guid("dc3d8822-1dec-4569-a5c7-77faea561d56"),
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("d8d43af0-02e3-4e58-88fb-7e2260fa06de"),
                            Brand = "Kryddmästarna",
                            Description = "Färsk och pepprig persilja som passar utmärkt till att krydda soppor, såser, potatis och sallader.",
                            Image = "parsley.jpg",
                            IsForLegalAge = false,
                            Name = "Persilja",
                            Price = 16.00m,
                            ProductCategoryId = new Guid("dc3d8822-1dec-4569-a5c7-77faea561d56"),
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("67a4d4d0-b6e0-4f4e-a6b1-4ef857d821b3"),
                            Brand = "Kryddmästarna",
                            Description = "Aromatisk och citrusliknande koriander som passar utmärkt till att krydda asiatiska rätter, curry, salsa och guacamole.",
                            Image = "coriander.jpg",
                            IsForLegalAge = false,
                            Name = "Koriander",
                            Price = 15.00m,
                            ProductCategoryId = new Guid("dc3d8822-1dec-4569-a5c7-77faea561d56"),
                            Stock = 55
                        },
                        new
                        {
                            Id = new Guid("d03817ec-d049-4903-b026-84c9d33b6f14"),
                            Brand = "Kryddmästarna",
                            Description = "Färsk och uppfriskande mynta som passar utmärkt till att krydda drycker, desserter, sallader och såser.",
                            Image = "mint.jpg",
                            IsForLegalAge = false,
                            Name = "Mynta",
                            Price = 14.00m,
                            ProductCategoryId = new Guid("dc3d8822-1dec-4569-a5c7-77faea561d56"),
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("0b8d1a2a-bf8c-44d8-8109-741e21962a7b"),
                            Brand = "Kryddmästarna",
                            Description = "Aromatisk och jordig salvia som passar utmärkt till att krydda kyckling, kalkon, soppa och såser.",
                            Image = "sage.jpg",
                            IsForLegalAge = false,
                            Name = "Salvia",
                            Price = 18.00m,
                            ProductCategoryId = new Guid("dc3d8822-1dec-4569-a5c7-77faea561d56"),
                            Stock = 45
                        },
                        new
                        {
                            Id = new Guid("bf7c6b13-778a-437b-a1b2-54d81aa18d7f"),
                            Brand = "Kryddmästarna",
                            Description = "Doftande och blommig lavendel som passar utmärkt till att krydda bakverk, desserter, te och marinader.",
                            Image = "lavender.jpg",
                            IsForLegalAge = false,
                            Name = "Lavendel",
                            Price = 20.00m,
                            ProductCategoryId = new Guid("dc3d8822-1dec-4569-a5c7-77faea561d56"),
                            Stock = 35
                        },
                        new
                        {
                            Id = new Guid("cdaa001f-1848-4ff2-b6dc-8e92b1e59d01"),
                            Brand = "Schwartz",
                            Description = "Schwartz Ground Black Pepper är en kryddig och aromatisk peppar av hög kvalitet. Perfekt för att ge en rik och robust smak till en mängd olika rätter.",
                            Image = "schwartz-black-pepper.jpg",
                            IsForLegalAge = false,
                            Name = "Schwartz Ground Black Pepper",
                            Price = 25.00m,
                            ProductCategoryId = new Guid("5ac3f10e-8d41-4e6b-bdb6-1496f00ce57a"),
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("ad82dd68-e180-46a7-aa3b-bf8cd908e686"),
                            Brand = "McCormick",
                            Description = "McCormick Pure Ground Black Pepper är en finmald och kraftfull peppar som ger en djup och fyllig smak till en mängd olika maträtter. Perfekt för att krydda både kött och grönsaker.",
                            Image = "mccormick-black-pepper.jpg",
                            IsForLegalAge = false,
                            Name = "McCormick Pure Ground Black Pepper",
                            Price = 30.00m,
                            ProductCategoryId = new Guid("5ac3f10e-8d41-4e6b-bdb6-1496f00ce57a"),
                            Stock = 120
                        },
                        new
                        {
                            Id = new Guid("b52234d3-d85f-47b5-89ad-d26118d00aaf"),
                            Brand = "Simply Organic",
                            Description = "Simply Organic Black Pepper är en ekologisk och hållbart producerad peppar av högsta kvalitet. Perfekt för att krydda dina favoriträtter med en naturlig och distinkt smak.",
                            Image = "simply-organic-black-pepper.jpg",
                            IsForLegalAge = false,
                            Name = "Simply Organic Black Pepper",
                            Price = 28.00m,
                            ProductCategoryId = new Guid("5ac3f10e-8d41-4e6b-bdb6-1496f00ce57a"),
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("d5e6f4d9-85b7-478b-b351-f4a8c063b86c"),
                            Brand = "Badia",
                            Description = "Badia Ground Black Pepper är en kryddig och aromatisk peppar av hög kvalitet som ger en rik och distinkt smak till dina maträtter. Perfekt för att krydda både sallader och såser.",
                            Image = "badia-black-pepper.jpg",
                            IsForLegalAge = false,
                            Name = "Badia Ground Black Pepper",
                            Price = 22.00m,
                            ProductCategoryId = new Guid("5ac3f10e-8d41-4e6b-bdb6-1496f00ce57a"),
                            Stock = 90
                        },
                        new
                        {
                            Id = new Guid("3e7ac9e1-c276-4aee-a6b9-68d6898f2b70"),
                            Brand = "Frontier Co-op",
                            Description = "Frontier Co-op Organic Tellicherry Black Peppercorns är handplockade och ekologiskt odlade svarta pepparkorn av högsta kvalitet. Perfekt för att mala till färskt kryddpulver som ger en intensiv och robust smak till dina rätter.",
                            Image = "frontier-coop-black-pepper.jpg",
                            IsForLegalAge = false,
                            Name = "Frontier Co-op Organic Tellicherry Black Peppercorns",
                            Price = 35.00m,
                            ProductCategoryId = new Guid("5ac3f10e-8d41-4e6b-bdb6-1496f00ce57a"),
                            Stock = 110
                        },
                        new
                        {
                            Id = new Guid("802d0199-3cd8-4a0d-8fa7-c52b46b0d936"),
                            Brand = "Spice Islands",
                            Description = "Spice Islands Ground Black Pepper är en finmald och aromatisk peppar som ger en rik och robust smak till dina favoriträtter. Perfekt för att krydda både kött och grönsaker.",
                            Image = "spice-islands-black-pepper.jpg",
                            IsForLegalAge = false,
                            Name = "Spice Islands Ground Black Pepper",
                            Price = 32.00m,
                            ProductCategoryId = new Guid("5ac3f10e-8d41-4e6b-bdb6-1496f00ce57a"),
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("3bc0101f-1aa3-46e8-8a62-86e9467ff376"),
                            Brand = "Penzey's",
                            Description = "Penzey's Extra Coarse Ground Black Pepper är en grovmald och kryddig peppar som ger en intensiv och fyllig smak till dina maträtter. Perfekt för att använda som en kryddig rub för grillat kött eller fisk.",
                            Image = "penzeys-black-pepper.jpg",
                            IsForLegalAge = false,
                            Name = "Penzey's Extra Coarse Ground Black Pepper",
                            Price = 30.00m,
                            ProductCategoryId = new Guid("5ac3f10e-8d41-4e6b-bdb6-1496f00ce57a"),
                            Stock = 90
                        },
                        new
                        {
                            Id = new Guid("9c9cbf77-af8b-4224-b4e8-365517d17027"),
                            Brand = "Morton & Bassett",
                            Description = "Morton & Bassett Organic Black Peppercorns är handplockade och ekologiskt odlade svarta pepparkorn av hög kvalitet. Perfekt för att mala till färskt kryddpulver som ger en intensiv och kryddig smak till dina maträtter.",
                            Image = "morton-bassett-black-pepper.jpg",
                            IsForLegalAge = false,
                            Name = "Morton & Bassett Organic Black Peppercorns",
                            Price = 38.00m,
                            ProductCategoryId = new Guid("5ac3f10e-8d41-4e6b-bdb6-1496f00ce57a"),
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("71ef1e7b-52d9-48df-91f5-0819aebc9b4e"),
                            Brand = "Olde Thompson",
                            Description = "Olde Thompson Organic Black Pepper är en kryddig och aromatisk peppar av hög kvalitet som ger en rik och distinkt smak till dina favoriträtter. Perfekt för att krydda både kött och grönsaker.",
                            Image = "olde-thompson-black-pepper.jpg",
                            IsForLegalAge = false,
                            Name = "Olde Thompson Organic Black Pepper",
                            Price = 34.00m,
                            ProductCategoryId = new Guid("5ac3f10e-8d41-4e6b-bdb6-1496f00ce57a"),
                            Stock = 85
                        },
                        new
                        {
                            Id = new Guid("19c7438b-75eb-43ff-8e5b-75d134142f64"),
                            Brand = "Simply Organic",
                            Description = "Simply Organic Whole Black Peppercorns är handplockade och ekologiskt odlade svarta pepparkorn av hög kvalitet. Perfekt för att mala till färskt kryddpulver som ger en kraftfull och robust smak till dina rätter.",
                            Image = "simply-organic-black-peppercorns.jpg",
                            IsForLegalAge = false,
                            Name = "Simply Organic Whole Black Peppercorns",
                            Price = 40.00m,
                            ProductCategoryId = new Guid("5ac3f10e-8d41-4e6b-bdb6-1496f00ce57a"),
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("c5ee9149-109f-48c6-b5bc-1de8224b9073"),
                            Brand = "Kryddmästarna",
                            Description = "En söt och syrlig balsamvinäger som är perfekt för att dressa sallader, grönsaker och grillat kött.",
                            Image = "balsamic-vinegar.jpg",
                            IsForLegalAge = false,
                            Name = "Balsamvinäger",
                            Price = 25.00m,
                            ProductCategoryId = new Guid("496adb77-621e-4abf-9fc9-8cd92a15e0f8"),
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("e9d8700d-98a3-4054-a4f3-f9fe779ef07d"),
                            Brand = "Kryddmästarna",
                            Description = "En kvalitativ och smakrik extra jungfruolivolja som är perfekt för att dressa sallader, pasta och bröd.",
                            Image = "olive-oil.jpg",
                            IsForLegalAge = false,
                            Name = "Olivolja",
                            Price = 30.00m,
                            ProductCategoryId = new Guid("496adb77-621e-4abf-9fc9-8cd92a15e0f8"),
                            Stock = 45
                        },
                        new
                        {
                            Id = new Guid("ba791d95-5d46-4d89-b9c8-2919c063be45"),
                            Brand = "Kryddmästarna",
                            Description = "En aromatisk och frisk citronpepparblandning som är perfekt för att krydda sallader, fisk och kyckling.",
                            Image = "lemon-pepper.jpg",
                            IsForLegalAge = false,
                            Name = "Citronpeppar",
                            Price = 18.00m,
                            ProductCategoryId = new Guid("496adb77-621e-4abf-9fc9-8cd92a15e0f8"),
                            Stock = 55
                        },
                        new
                        {
                            Id = new Guid("67684b6b-7da3-4846-b45c-bd0a46002b27"),
                            Brand = "Kryddmästarna",
                            Description = "En krämig och smakrik Caesardressing som är perfekt för att toppa sallader, wraps och sandwichar.",
                            Image = "caesar-dressing.jpg",
                            IsForLegalAge = false,
                            Name = "Caesardressing",
                            Price = 20.00m,
                            ProductCategoryId = new Guid("496adb77-621e-4abf-9fc9-8cd92a15e0f8"),
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("39265ae1-9d07-4e90-b826-9835609ffecb"),
                            Brand = "Kryddmästarna",
                            Description = "Knapriga och krämiga hasselnötter som är perfekta för att strö över sallader, frukostblandningar och bakverk.",
                            Image = "hazelnuts.jpg",
                            IsForLegalAge = false,
                            Name = "Hasselnötter",
                            Price = 22.00m,
                            ProductCategoryId = new Guid("496adb77-621e-4abf-9fc9-8cd92a15e0f8"),
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("bf8d1562-1cb1-4e02-90eb-927e204ccf2e"),
                            Brand = "Kryddmästarna",
                            Description = "En robust och aromatisk rödvinsvinäger som är perfekt för att dressa sallader, marinader och såser.",
                            Image = "red-wine-vinegar.jpg",
                            IsForLegalAge = false,
                            Name = "Rödvinsvinäger",
                            Price = 25.00m,
                            ProductCategoryId = new Guid("496adb77-621e-4abf-9fc9-8cd92a15e0f8"),
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("88a2c83a-f3f8-49a4-99c2-50b9110eb518"),
                            Brand = "Kryddmästarna",
                            Description = "Smakrika och knapriga sesamfrön som är perfekta för att strö över sallader, nudlar och asiatiska rätter.",
                            Image = "sesame-seeds.jpg",
                            IsForLegalAge = false,
                            Name = "Sesamfrön",
                            Price = 20.00m,
                            ProductCategoryId = new Guid("496adb77-621e-4abf-9fc9-8cd92a15e0f8"),
                            Stock = 45
                        },
                        new
                        {
                            Id = new Guid("07dd33c3-8a87-4d30-8d84-2d40376c0e43"),
                            Brand = "Kryddmästarna",
                            Description = "Färska och krispiga rödlökar som är perfekta för att tillsätta smak och knaprighet till sallader, tacos och burgare.",
                            Image = "red-onion.jpg",
                            IsForLegalAge = false,
                            Name = "Rödlök",
                            Price = 18.00m,
                            ProductCategoryId = new Guid("496adb77-621e-4abf-9fc9-8cd92a15e0f8"),
                            Stock = 55
                        },
                        new
                        {
                            Id = new Guid("47b409ec-32e8-4721-a091-0048e7f7fd4e"),
                            Brand = "Kryddmästarna",
                            Description = "Knaperiga och smakrika krutonger som är perfekta för att strö över sallader och soppor eller som ett krispigt tillbehör till dina favoriträtter.",
                            Image = "croutons.jpg",
                            IsForLegalAge = false,
                            Name = "Krutonger",
                            Price = 20.00m,
                            ProductCategoryId = new Guid("496adb77-621e-4abf-9fc9-8cd92a15e0f8"),
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("e4c2aacc-cd08-4597-97a0-ec7a3d44697c"),
                            Brand = "Kryddmästarna",
                            Description = "En härlig blandning av kryddor och örter som är perfekt för att ge sallader en extra smakboost.",
                            Image = "salad-seasoning.jpg",
                            IsForLegalAge = false,
                            Name = "Salladskrydda",
                            Price = 15.00m,
                            ProductCategoryId = new Guid("496adb77-621e-4abf-9fc9-8cd92a15e0f8"),
                            Stock = 65
                        });
                });

            modelBuilder.Entity("Commerce.Models.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c00f03e-e62f-430b-92c2-df95913a192b"),
                            ProductCategoryName = "Dricka"
                        },
                        new
                        {
                            Id = new Guid("cc74f91b-91ac-4632-8636-15b7722fc3e7"),
                            ProductCategoryName = "Energi Dricka"
                        },
                        new
                        {
                            Id = new Guid("d58f87f4-7378-447a-93d4-b888fbecfb6e"),
                            ProductCategoryName = "LösGodis"
                        },
                        new
                        {
                            Id = new Guid("87242b00-6f72-4caa-b687-b105001e1ad3"),
                            ProductCategoryName = "VanligtGodis"
                        },
                        new
                        {
                            Id = new Guid("1faa3b8a-6f3d-4ad3-b21a-6e43887e4a57"),
                            ProductCategoryName = "Cigaretter"
                        },
                        new
                        {
                            Id = new Guid("572d1a92-5e15-4602-b150-01a2923224c6"),
                            ProductCategoryName = "Snus"
                        },
                        new
                        {
                            Id = new Guid("5ac3f10e-8d41-4e6b-bdb6-1496f00ce57a"),
                            ProductCategoryName = "Peppar"
                        },
                        new
                        {
                            Id = new Guid("aba0e880-9edb-44a2-96d8-a0cf508b5ef2"),
                            ProductCategoryName = "Örtmixer"
                        },
                        new
                        {
                            Id = new Guid("d72b840d-44ab-4205-b526-02111d87691b"),
                            ProductCategoryName = "Grillkryddor"
                        },
                        new
                        {
                            Id = new Guid("dc3d8822-1dec-4569-a5c7-77faea561d56"),
                            ProductCategoryName = "Örter"
                        },
                        new
                        {
                            Id = new Guid("496adb77-621e-4abf-9fc9-8cd92a15e0f8"),
                            ProductCategoryName = "Salladskryddor"
                        });
                });

            modelBuilder.Entity("Commerce.Models.Product", b =>
                {
                    b.HasOne("Commerce.Models.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Commerce.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
